# Generated by Django 2.2.1 on 2019-05-21 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_categories_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название подкатегории продукта')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id_product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_categories_app.ProductCategory')),
            ],
            options={
                'ordering': ['-name', '-modified', '-created'],
            },
        ),
    ]
