# Generated by Django 2.2.1 on 2019-05-21 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_subcategories_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'ordering': ['-name', '-created', '-modified']},
        ),
        migrations.RenameField(
            model_name='productsubcategory',
            old_name='id_product_category',
            new_name='product_category',
        ),
    ]
