# Generated by Django 2.2.1 on 2019-05-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_subcategories_app', '0003_auto_20190521_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название подкатегории продукта'),
        ),
    ]
