# Generated by Django 2.1.1 on 2019-05-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_subcategories_app', '0005_auto_20190522_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'ordering': ['-name', '-created', '-modified']},
        ),
    ]
