# Generated by Django 2.1.1 on 2019-05-22 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_subcategories_app', '0006_auto_20190522_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategory',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_categories_app.ProductCategory', verbose_name='Категория продукта'),
        ),
    ]
