# Generated by Django 2.1.1 on 2019-05-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_subcategories_app', '0007_auto_20190522_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'ordering': ['-product_category', '-name', '-created', '-modified']},
        ),
    ]
