# Generated by Django 2.1.1 on 2019-05-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_subcategories_app', '0008_auto_20190522_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategory',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
