# Generated by Django 2.1.1 on 2019-05-23 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products_app', '0008_auto_20190523_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название изображения')),
                ('description', models.CharField(max_length=128, verbose_name='Описание изображения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.Product', verbose_name='Продукт')),
            ],
            options={
                'ordering': ['-product', '-name', '-created', '-modified'],
            },
        ),
    ]
