# Generated by Django 2.1.1 on 2019-05-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=128, verbose_name='Описание изображения'),
        ),
    ]
