# Generated by Django 2.2.1 on 2019-05-21 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-name', '-created', '-modified']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id_product_subcategory',
            new_name='product_subcategory',
        ),
    ]
