# Generated by Django 2.1.1 on 2019-05-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_product_product_measure_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmeasureunit',
            name='full_name',
            field=models.CharField(default=0, max_length=32, unique=True, verbose_name='Полное наименование'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmeasureunit',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='Наименование'),
        ),
    ]
