# Generated by Django 2.1.1 on 2019-05-28 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_auto_20190528_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeedbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(verbose_name='Отзыв')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('deleted', models.BooleanField(verbose_name='Удален')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.Product', verbose_name='Продукт')),
            ],
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Наименование'),
        ),
    ]
