# Generated by Django 2.2.1 on 2019-05-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_auto_20190521_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristic',
            field=models.CharField(blank=True, max_length=512, verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='product',
            name='consist',
            field=models.CharField(blank=True, max_length=512, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_name',
            field=models.CharField(max_length=128, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Наименование'),
        ),
    ]
