# Generated by Django 2.1.1 on 2019-05-22 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0006_auto_20190522_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-product_subcategory', '-name', '-created', '-modified']},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_subcategories_app.ProductSubcategory', verbose_name='Подкатегория продукта'),
        ),
    ]
