# Generated by Django 2.1.1 on 2019-05-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0008_auto_20190523_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristic',
            field=models.TextField(blank=True, verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='product',
            name='consist',
            field=models.TextField(blank=True, verbose_name='Состав'),
        ),
    ]
