# Generated by Django 2.2.1 on 2019-05-21 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_categories_app', '0003_auto_20190521_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={},
        ),
    ]
