# Generated by Django 2.1.1 on 2019-05-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_categories_app', '0005_auto_20190521_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={},
        ),
    ]
