# Generated by Django 2.1.1 on 2019-05-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_categories_app', '0007_auto_20190522_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['-created', '-modified']},
        ),
    ]
