# Generated by Django 2.1.1 on 2019-05-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_categories_app', '0009_auto_20190522_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['-title', '-created', '-modified']},
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='name',
            new_name='title',
        ),
    ]
