# Generated by Django 2.1.1 on 2019-05-22 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_categories_app', '0011_auto_20190522_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='title',
            new_name='name',
        ),
    ]
