# Generated by Django 2.1.1 on 2019-05-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_categories_app', '0013_auto_20190522_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
